env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
  - prettier
overrides: []
parserOptions:
  project: "./tsconfig.json"
plugins:
  - react
rules:
  "react/jsx-uses-react": off
  "react/react-in-jsx-scope": off
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-unused-vars": off
  "@typescript-eslint/consistent-type-imports": off
  "@typescript-eslint/consistent-type-assertions": off
